### ISSUE TITLE
Add option for signs to preserve text when broken.

### ISSUE THREAD

**Issue by RDKRACZ** [Ivan0xFF/BetterSignsAndFrames#8]

**Comment by Ivan0xFF** [comment]
Thanks for the suggestion. How exactly do you envision this working? 

I'm thinking something like:
1. You break a sign
2. The sign's text is saved somewhere
3. You place a sign
4. The saved text is re-applied to that sign

Is this what you had it mind?

**Comment by RDKRACZ** [comment]
Yes
>The sign's text is saved somewhere

There was a mod like this already but I can't find it. It certainly is possible and I think you can just use vanilla functionality (nbt data) to achieve this. You can ctrl+middle click any tile entity to copy it with data like this
![image](https://user-images.githubusercontent.com/43277609/111053067-04134d00-8461-11eb-8ef7-fabebe784e71.png)

This sign after placing is already with some text. Just make it work in survival and when breaking.

**Comment by supersaiyansubtlety** [comment]
This is the mod: https://www.curseforge.com/minecraft/mc-mods/sign-retain

You don't have to save the text in some external location, it can be part of the item's nbt, even in vanilla (crtl-middle-click sign in creative). 

Though since it's already implemented in a fabric 1.16 mod I don't see the point of duplicating it here.

**Comment by RDKRACZ** [comment]
Then there is no purpose for this mod too because all these features are already in other mods like TinyTweaks or https://www.curseforge.com/minecraft/mc-mods/edit-sign

**Comment by supersaiyansubtlety** [comment]
Edit sign doesn't have click through and afaik tinyteaks only has clickthrough. 
I use this mod because it has both, trying to combine other mods with only one of these features each hasn't worked for me, *and* this one lets you stop the sign gui from opening when you place a sign.
 
I suspect sign retain is compatible with this one, but it's also probably a very easy change to make, and does appear to fit into the scope of this mod. 

But anyways, these are just my opinions and I'm not the mod author, I was just providing a bit of feedback.

**Comment by Ivan0xFF** [comment]
Merged in the latest 0.8 updated
